### ISSUE TITLE
Red background

### ISSUE THREAD

**Issue by yephny** [atahabaki/wordbook-android#51] opened 2021-11-09 20:44 UTC
It's difficult looking at a red background when you're typing out a word and its meaning. Please consider making the background black. 

I see that you're planning to add theme options that the user can choose from. You could make an option to change the red background if you prefer it the way it currently is.

**Comment by atahabaki** [comment] 2021-12-03 12:55
If I do that, the FAB's (the red plus + button) background should be black too... I'm already planing to create dynamic theming. But I'm having difficulties to choose from these:
 - I could just make a color picker, so the user could change only the accent color and the background (surface)...
 - Or I could give a dozen of options, so the user could change every background and foreground however the way want...
I'm dismissing this issue, 'cause it is almost a duplicate of the issue #26.
What's your opinion? That would help a lot...

**Comment by yephny** [comment] 2021-12-03 14:32
I think it makes sense to have a few simple theme options (like light, dark, black).

Yeah, this can be considered a duplicate of #26, I'm closing the issue.

**Closed as completed** 2021-12-03 14:32 UTC
Labels: ui, pr0, req, !fix
